name: py5
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=2.2.*
  - black=24.2.*
  - cairo=1.18.*
  - cairocffi=1.7.*
  - cairosvg=2.7.*
  - colour>=0.1.*
  - flake8=7.1.*
  - hatch=1.12.*
  - ipython=8.18.*
  - jedi=0.19.*
  - jpype1=1.5.*
  - jupyter=1.0.*
  - jupyter-book=1.0.*
  - jupyterlab=4.2.*
  - jupytext=1.16.*
  - line_profiler=4.1.*
  - matplotlib=3.9.*
  - numpy=1.26.*
  - pandas=2.2.*
  - pillow=10.2.*
  - pip
  - python=3.9.*
  - requests=2.31.*
  - shapely=2.0.*
  - trimesh=4.3.*
  - twine>=5.1.*
  - yarn>=4.3.*
  - pip:
    - bump2version==1.0.*
    - stackprinter==0.2.11
    - opencv-contrib-python>=4.10.*
