name: py5
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=2.3.*
  - black=25.1.*
  - cairo=1.18.*
  - cairocffi=1.7.*
  - cairosvg=2.8.*
  - colour>=0.1.*
  - flake8=7.1.*
  - hatch=1.14.*
  - ipython=8.37.*
  - jedi=0.19.*
  - jpype1=1.6.*
  - jupyter=1.1.*
  - jupyter-book=1.0.*
  - jupyterlab=4.4.*
  - jupytext=1.17.*
  - line_profiler=4.2.*
  - matplotlib=3.10.*
  - numpy=2.2.*
  - pandas=2.3.*
  - pillow=11.0.*
  - pip
  - python=3.10.*
  - requests=2.32.*
  - shapely=2.0.*
  - trimesh=4.6.*
  - twine>=6.1.*
  - pip:
    - stackprinter==0.2.12
    - opencv-contrib-python>=4.12
